import {
  Code2, Globe, Smartphone, Layers, Palette, Sparkles,
  Brush, PenTool, Megaphone, Search, ThumbsUp, ShoppingCart,
  Bot, Cloud,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

export interface ServiceData {
  slug: string;
  category: "development" | "design" | "marketing";
  title: string;
  tagline: string;
  heroDescription: string;
  icon: LucideIcon;
  accentColor: string;
  heroStats: { value: string; label: string }[];
  whatWeDo: {
    heading: string;
    body: string;
    bullets: string[];
  };
  offerings: { title: string; description: string }[];
  process: { step: string; title: string; description: string }[];
  techStack: string[];
  whyUs: { title: string; description: string }[];
}

export const servicesData: ServiceData[] = [
  {
    slug: "custom-software-development",
    category: "development",
    title: "Custom Software Development",
    tagline: "Software built exactly for the way you work.",
    heroDescription: "Off-the-shelf tools can only take you so far. We design and engineer bespoke software that fits your workflows, scales with your growth, and gives your business a genuine competitive edge.",
    icon: Code2,
    accentColor: "bg-[#C4B5FD]",
    heroStats: [
      { value: "50+", label: "Custom builds delivered" },
      { value: "99%", label: "On-time delivery rate" },
      { value: "3+", label: "Years of expertise" },
    ],
    whatWeDo: {
      heading: "Software that solves the problem no product can.",
      body: "When your business has a problem that existing tools don't fully solve, custom software is the answer. We work closely with you to understand your processes, constraints, and goals — then engineer a solution that fits precisely.",
      bullets: [
        "Full discovery and requirements workshops",
        "Architecture design and tech stack selection",
        "Agile, iterative development with regular demos",
        "QA, security testing, and performance optimisation",
        "Deployment, documentation, and post-launch support",
      ],
    },
    offerings: [
      { title: "Web Applications", description: "Scalable browser-based tools and platforms built for real workflows." },
      { title: "Internal Tooling", description: "Replace messy spreadsheets and manual processes with clean internal systems." },
      { title: "API Development", description: "Robust REST and GraphQL APIs that connect your services reliably." },
      { title: "System Integration", description: "Connect your existing tools, databases, and third-party services seamlessly." },
      { title: "Legacy Modernisation", description: "Rebuild ageing systems with modern architecture while preserving business logic." },
      { title: "Automation", description: "Eliminate repetitive manual work with intelligent workflow automation." },
    ],
    process: [
      { step: "01", title: "Discovery", description: "We map your business goals, user needs, and technical constraints before writing a line of code." },
      { step: "02", title: "Architecture", description: "We design the right data model, tech stack, and system boundaries for your problem." },
      { step: "03", title: "Build", description: "Iterative sprints with working software at the end of every cycle." },
      { step: "04", title: "Test & Harden", description: "Automated tests, security audits, and performance checks before anything ships." },
      { step: "05", title: "Deploy", description: "CI/CD pipelines, cloud infrastructure, and a smooth go-live with zero surprises." },
      { step: "06", title: "Support", description: "Ongoing maintenance, monitoring, and feature iterations as your needs evolve." },
    ],
    techStack: ["TypeScript", "Node.js", "Next.js", "React", "PostgreSQL", "MongoDB", "Docker", "AWS", "REST APIs", "GraphQL"],
    whyUs: [
      { title: "We own the outcome", description: "We don't just write tickets — we take responsibility for the end result working in your business." },
      { title: "No black-box development", description: "Regular demos, open code, and plain-English updates at every stage." },
      { title: "Built to last", description: "Clean architecture, thorough documentation, and code your next developer won't curse." },
      { title: "Flexible engagement", description: "Fixed-scope projects, ongoing retainers, or staff augmentation — whatever fits your situation." },
    ],
  },
  {
    slug: "web-development",
    category: "development",
    title: "Web Development",
    tagline: "Fast, beautiful websites that actually convert.",
    heroDescription: "Your website is your most important sales tool. We build performant, accessible, and visually sharp web experiences that reflect your brand and drive real business outcomes.",
    icon: Globe,
    accentColor: "bg-[#BAE6FD]",
    heroStats: [
      { value: "40+", label: "Websites launched" },
      { value: "98+", label: "Avg Lighthouse score" },
      { value: "3+", label: "Years building for the web" },
    ],
    whatWeDo: {
      heading: "Websites engineered to perform, not just to look good.",
      body: "We combine sharp design with technical rigour to build websites that load fast, rank well, and turn visitors into customers.",
      bullets: [
        "Custom design tailored to your brand",
        "Server-side rendering for speed and SEO",
        "Fully responsive across all devices",
        "CMS integration so you control your content",
        "Analytics and conversion tracking built in",
      ],
    },
    offerings: [
      { title: "Marketing Websites", description: "Conversion-focused sites that tell your story and generate leads." },
      { title: "Landing Pages", description: "High-performing pages built around specific campaigns and audiences." },
      { title: "Corporate Websites", description: "Professional, scalable web presence for established businesses." },
      { title: "CMS-Powered Sites", description: "Full editorial control via Sanity, Contentful, or WordPress." },
      { title: "Web Portals", description: "Authenticated user experiences with dashboards and dynamic content." },
      { title: "Website Redesigns", description: "Modernise an existing site without losing SEO equity or brand recognition." },
    ],
    process: [
      { step: "01", title: "Strategy", description: "Understand your audience, goals, and the story your site needs to tell." },
      { step: "02", title: "Design", description: "Wireframes then high-fidelity designs — all approved before development starts." },
      { step: "03", title: "Development", description: "Clean, semantic code built with performance and accessibility as defaults." },
      { step: "04", title: "Content", description: "Copywriting, imagery, and CMS setup so the site is ready from day one." },
      { step: "05", title: "Testing", description: "Cross-browser QA, speed audits, and mobile checks across real devices." },
      { step: "06", title: "Launch & SEO", description: "Smooth deployment with structured data, sitemaps, and analytics configured." },
    ],
    techStack: ["Next.js", "React", "TypeScript", "Tailwind CSS", "Sanity", "WordPress", "Vercel", "Cloudflare"],
    whyUs: [
      { title: "Performance is non-negotiable", description: "We optimise for Core Web Vitals from the first line of code, not as an afterthought." },
      { title: "Design and dev under one roof", description: "No handoff friction — the team that designs your site also builds it." },
      { title: "Content-ready on launch day", description: "We set up your CMS and train your team so you're publishing from day one." },
      { title: "Long-term partnership", description: "We stay available for updates, improvements, and new features as you grow." },
    ],
  },
  {
    slug: "mobile-app-development",
    category: "development",
    title: "Mobile App Development",
    tagline: "Apps your users will actually want to open.",
    heroDescription: "From concept to App Store, we build iOS and Android apps that are fast, intuitive, and built to retain users — not just attract them.",
    icon: Smartphone,
    accentColor: "bg-[#A7F3D0]",
    heroStats: [
      { value: "20+", label: "Apps shipped" },
      { value: "4.8★", label: "Average app store rating" },
      { value: "iOS & Android", label: "Full coverage" },
    ],
    whatWeDo: {
      heading: "Mobile experiences built around how people actually use their phones.",
      body: "Great apps feel effortless. We design and build mobile products with obsessive attention to UX — because the best features in the world don't matter if the app is frustrating to use.",
      bullets: [
        "Native iOS (Swift) and Android (Kotlin) development",
        "Cross-platform with React Native or Flutter",
        "Backend APIs and real-time features",
        "App Store and Google Play submission",
        "Push notifications, analytics, and crash monitoring",
      ],
    },
    offerings: [
      { title: "iOS Apps", description: "Native Swift development following Apple's Human Interface Guidelines." },
      { title: "Android Apps", description: "Performant Kotlin apps built to Google's Material Design standards." },
      { title: "Cross-Platform Apps", description: "Single codebase for both platforms using React Native or Flutter." },
      { title: "MVP Development", description: "Get to market fast with a focused, well-built first version." },
      { title: "App Redesigns", description: "Modernise an existing app without rebuilding everything from scratch." },
      { title: "Backend & APIs", description: "The server-side infrastructure your app needs to work reliably at scale." },
    ],
    process: [
      { step: "01", title: "Product Definition", description: "Define your core user flows, must-have features, and success metrics." },
      { step: "02", title: "UX Design", description: "Wireframes and interactive prototypes tested with real users before building." },
      { step: "03", title: "UI Design", description: "Pixel-perfect visual design that meets platform guidelines and feels premium." },
      { step: "04", title: "Development", description: "Iterative builds with TestFlight/beta distribution so you see progress continuously." },
      { step: "05", title: "QA & Testing", description: "Device testing, edge-case coverage, and performance profiling." },
      { step: "06", title: "Launch & Growth", description: "App store optimisation, analytics setup, and post-launch iteration." },
    ],
    techStack: ["React Native", "Flutter", "Swift", "Kotlin", "Expo", "Firebase", "Node.js", "AWS"],
    whyUs: [
      { title: "UX-first approach", description: "We prototype and validate flows before writing a line of production code." },
      { title: "Platform expertise", description: "We follow native design guidelines so your app feels right on every device." },
      { title: "End-to-end delivery", description: "Design, development, and App Store submission — all handled by one team." },
      { title: "Post-launch support", description: "OS updates, new devices, and user feedback — we stay with you after launch." },
    ],
  },
  {
    slug: "saas-development",
    category: "development",
    title: "SaaS Development",
    tagline: "Build the product your market is waiting for.",
    heroDescription: "We help founders and product teams design, build, and scale SaaS products — from zero to launch, and from launch to product-market fit.",
    icon: Layers,
    accentColor: "bg-[#FDE68A]",
    heroStats: [
      { value: "15+", label: "SaaS products launched" },
      { value: "Multi-tenant", label: "Architecture expertise" },
      { value: "Scalable", label: "From day one" },
    ],
    whatWeDo: {
      heading: "SaaS built to scale, not just to ship.",
      body: "Building a SaaS product is different from building a website. It needs multi-tenancy, subscription billing, role-based access, and an architecture that doesn't collapse under growth.",
      bullets: [
        "Multi-tenant architecture design",
        "Subscription billing with Stripe",
        "Role-based access control and team management",
        "Onboarding flows that activate users fast",
        "Admin dashboards and analytics",
      ],
    },
    offerings: [
      { title: "MVP & Prototype", description: "Validate your idea with a focused build before committing to full scale." },
      { title: "Full Product Build", description: "End-to-end SaaS development from architecture to production deployment." },
      { title: "Billing & Subscriptions", description: "Stripe integration with plans, trials, upgrades, and invoicing." },
      { title: "Multi-Tenant Systems", description: "Secure data isolation and tenant management built properly." },
      { title: "Dashboards & Analytics", description: "Usage metrics, reporting, and data visualisation for your users." },
      { title: "API & Integrations", description: "Public APIs, webhooks, and integrations with tools your users already use." },
    ],
    process: [
      { step: "01", title: "Product Strategy", description: "Define your ICP, core value prop, and the minimum viable feature set." },
      { step: "02", title: "Architecture", description: "Design the data model and system architecture that will scale with you." },
      { step: "03", title: "Design", description: "Onboarding flows, dashboards, and UI designed for activation and retention." },
      { step: "04", title: "Build", description: "Iterative development with weekly demos and a live staging environment." },
      { step: "05", title: "Beta & Testing", description: "Private beta, user feedback loops, and performance hardening." },
      { step: "06", title: "Launch & Scale", description: "Production deployment, monitoring setup, and growth iteration." },
    ],
    techStack: ["Next.js", "Node.js", "PostgreSQL", "Stripe", "Redis", "Docker", "AWS", "TypeScript"],
    whyUs: [
      { title: "We understand SaaS economics", description: "We build for activation, retention, and expansion — not just feature delivery." },
      { title: "Architecture that scales", description: "Multi-tenant from day one, so you don't have to rebuild when you grow." },
      { title: "Billing handled properly", description: "Stripe integration that covers trials, proration, upgrades, and failed payments." },
      { title: "Founder-friendly process", description: "We move fast, communicate clearly, and treat your runway with respect." },
    ],
  },
  {
    slug: "ui-ux-design",
    category: "design",
    title: "UI/UX Design",
    tagline: "Interfaces that feel obvious to use.",
    heroDescription: "Great design isn't decoration — it's the difference between a product people love and one they abandon. We design digital experiences that are intuitive, accessible, and unmistakably on-brand.",
    icon: Palette,
    accentColor: "bg-[#C4B5FD]",
    heroStats: [
      { value: "60+", label: "Products designed" },
      { value: "UX + UI", label: "End-to-end design" },
      { value: "Figma-first", label: "Handoff ready" },
    ],
    whatWeDo: {
      heading: "Design that solves problems, not just looks good.",
      body: "We approach every design project with user research and business goals in equal measure. The result is an interface that converts, retains, and delights.",
      bullets: [
        "User research and persona development",
        "Information architecture and user flows",
        "Wireframing and interactive prototyping",
        "High-fidelity UI design in Figma",
        "Design system and component library creation",
      ],
    },
    offerings: [
      { title: "Product Design", description: "End-to-end design for web and mobile products, from research to final UI." },
      { title: "UX Audit", description: "Identify friction, drop-off points, and opportunities in your existing product." },
      { title: "Design Systems", description: "A shared component library that keeps your product consistent at scale." },
      { title: "Prototyping", description: "Clickable prototypes for user testing and stakeholder alignment before dev." },
      { title: "Responsive Design", description: "Pixel-perfect layouts that work beautifully across every screen size." },
      { title: "Design-to-Dev Handoff", description: "Developer-ready Figma files with specs, assets, and interaction notes." },
    ],
    process: [
      { step: "01", title: "Research", description: "User interviews, competitor analysis, and heuristic evaluation." },
      { step: "02", title: "Information Architecture", description: "Site maps, user flows, and content hierarchy before design begins." },
      { step: "03", title: "Wireframes", description: "Low-fidelity layouts to validate structure and flows quickly." },
      { step: "04", title: "Visual Design", description: "High-fidelity UI that applies your brand system to every component." },
      { step: "05", title: "Prototype & Test", description: "Interactive prototypes tested with real users and iterated on." },
      { step: "06", title: "Handoff", description: "Annotated Figma files, exported assets, and developer walkthroughs." },
    ],
    techStack: ["Figma", "Adobe XD", "FigJam", "Maze", "Hotjar", "Lottie", "Zeplin"],
    whyUs: [
      { title: "Research-driven decisions", description: "Every design choice traces back to a user need or business goal." },
      { title: "Design and dev alignment", description: "We work alongside developers, so designs are always feasible and implementation-ready." },
      { title: "Systems thinking", description: "We design components, not screens — so your product stays consistent as it grows." },
      { title: "Accessibility by default", description: "WCAG-compliant design that works for every user, on every device." },
    ],
  },
  {
    slug: "brand-identity",
    category: "design",
    title: "Brand Identity",
    tagline: "A brand that people remember — and trust.",
    heroDescription: "Your brand is more than a logo. It's the sum of every impression you make. We build cohesive brand identities that communicate who you are, what you stand for, and why you're different.",
    icon: Sparkles,
    accentColor: "bg-[#FDE68A]",
    heroStats: [
      { value: "30+", label: "Brands built" },
      { value: "Strategy", label: "Led, not logo-first" },
      { value: "Full", label: "Brand system delivery" },
    ],
    whatWeDo: {
      heading: "Brand identity built on strategy, not just aesthetics.",
      body: "A great brand starts with clarity — who you are, who you serve, and what makes you different. We do that strategic work first, then translate it into a visual identity system that's consistent, memorable, and built to last.",
      bullets: [
        "Brand strategy and positioning",
        "Logo design and visual identity",
        "Typography and colour system",
        "Brand guidelines and usage rules",
        "Application across all touchpoints",
      ],
    },
    offerings: [
      { title: "Brand Strategy", description: "Positioning, messaging hierarchy, and the narrative that drives all design decisions." },
      { title: "Logo Design", description: "A mark that works at every size, in every context, in every colour scheme." },
      { title: "Visual Identity System", description: "Colours, typography, iconography, and layout principles that work together." },
      { title: "Brand Guidelines", description: "A comprehensive document that keeps your brand consistent whoever's using it." },
      { title: "Brand Refresh", description: "Modernise an existing brand without losing the equity you've already built." },
      { title: "Brand Collateral", description: "Business cards, decks, email signatures, and every touchpoint applied." },
    ],
    process: [
      { step: "01", title: "Discovery", description: "Brand audit, competitor landscape, and stakeholder interviews." },
      { step: "02", title: "Strategy", description: "Positioning statement, tone of voice, and brand personality definition." },
      { step: "03", title: "Concept", description: "Two or three distinct creative directions presented with rationale." },
      { step: "04", title: "Design", description: "Develop the chosen direction into a full visual identity system." },
      { step: "05", title: "Application", description: "Apply the identity across your key touchpoints to see it in context." },
      { step: "06", title: "Delivery", description: "All files, guidelines, and an internal brand launch if needed." },
    ],
    techStack: ["Figma", "Adobe Illustrator", "Adobe InDesign", "Adobe Photoshop", "Brandpad"],
    whyUs: [
      { title: "Strategy before execution", description: "We won't sketch a logo until we know what it needs to say and to whom." },
      { title: "Built for application", description: "Every element is tested across real contexts — print, digital, dark backgrounds." },
      { title: "Long-term thinking", description: "We design identities that will still look right in ten years." },
      { title: "Cross-discipline team", description: "Strategists and designers working together, not in sequence." },
    ],
  },
  {
    slug: "graphic-design",
    category: "design",
    title: "Graphic Design",
    tagline: "Visual communication that stops the scroll.",
    heroDescription: "From social assets to pitch decks to print collateral, we create graphics that communicate your message clearly, look unmistakably on-brand, and hold up at any size.",
    icon: Brush,
    accentColor: "bg-[#A7F3D0]",
    heroStats: [
      { value: "500+", label: "Assets delivered" },
      { value: "Fast", label: "Turnaround" },
      { value: "Brand-consistent", label: "Every time" },
    ],
    whatWeDo: {
      heading: "Design that works as hard as you do.",
      body: "Good graphic design isn't just about making things look nice — it's about communicating the right message to the right audience in the right context.",
      bullets: [
        "Social media graphics and content templates",
        "Presentation and pitch deck design",
        "Print-ready marketing materials",
        "Email headers and newsletter design",
        "Infographics and data visualisation",
      ],
    },
    offerings: [
      { title: "Social Media Graphics", description: "Scroll-stopping assets sized and optimised for every platform." },
      { title: "Pitch Decks", description: "Investor and client presentations designed to land the meeting." },
      { title: "Print Collateral", description: "Brochures, flyers, banners, and signage that look great in the real world." },
      { title: "Infographics", description: "Complex data and ideas made clear and shareable through visual storytelling." },
      { title: "Email Design", description: "Branded email templates and newsletters that drive clicks." },
      { title: "Ad Creative", description: "Digital ad assets for Google, Meta, and LinkedIn campaigns." },
    ],
    process: [
      { step: "01", title: "Brief", description: "We capture the objective, audience, format requirements, and brand guidelines." },
      { step: "02", title: "Concept", description: "Initial directions presented for feedback before full production." },
      { step: "03", title: "Design", description: "Full execution of the approved direction with brand precision." },
      { step: "04", title: "Review", description: "Structured rounds of feedback with tracked revisions." },
      { step: "05", title: "Export", description: "Files delivered in every format you need." },
    ],
    techStack: ["Adobe Illustrator", "Adobe Photoshop", "Figma", "Adobe InDesign", "Canva Pro", "After Effects"],
    whyUs: [
      { title: "Brand consistency guaranteed", description: "Every asset goes through a brand-check before it leaves our hands." },
      { title: "Fast turnaround", description: "Most assets delivered within 48–72 hours without sacrificing quality." },
      { title: "Scalable retainer model", description: "Ongoing design support so you always have a designer on call." },
      { title: "Format expertise", description: "We know the specs for every platform and format — you don't have to." },
    ],
  },
  {
    slug: "digital-product-design",
    category: "design",
    title: "Digital Product Design",
    tagline: "Products people can't stop using.",
    heroDescription: "We design digital products — dashboards, tools, platforms, and applications — that are intuitive, efficient, and genuinely enjoyable to use.",
    icon: PenTool,
    accentColor: "bg-[#BFDBFE]",
    heroStats: [
      { value: "40+", label: "Products shipped" },
      { value: "Research", label: "Backed decisions" },
      { value: "System-first", label: "Design approach" },
    ],
    whatWeDo: {
      heading: "Designed for the user. Built for the business.",
      body: "Digital product design is the intersection of user research, systems thinking, and visual craft. We make sure every screen serves a clear purpose and every interaction feels natural.",
      bullets: [
        "End-to-end product design from research to handoff",
        "Design systems and component libraries",
        "Data-dense dashboards and complex UI patterns",
        "Onboarding and activation flow design",
        "Usability testing and iterative improvement",
      ],
    },
    offerings: [
      { title: "Dashboard Design", description: "Complex data made navigable, scannable, and actionable." },
      { title: "Onboarding Design", description: "First-run experiences that activate users and reduce churn." },
      { title: "Design Systems", description: "Scalable component libraries that keep product teams moving fast." },
      { title: "Enterprise UX", description: "Powerful tools that experienced users can master and new users can learn." },
      { title: "Interaction Design", description: "Micro-interactions, transitions, and states that make products feel polished." },
      { title: "Usability Testing", description: "Structured sessions that reveal where your product loses users." },
    ],
    process: [
      { step: "01", title: "Research", description: "User interviews, job stories, and existing product analysis." },
      { step: "02", title: "Flows", description: "Map every user journey and identify friction and opportunity." },
      { step: "03", title: "Wireframes", description: "Structure and hierarchy locked down before visual design begins." },
      { step: "04", title: "Design", description: "High-fidelity UI with interaction states, edge cases, and empty states covered." },
      { step: "05", title: "Test", description: "Usability sessions with target users, iterated until the experience is right." },
      { step: "06", title: "Handoff", description: "Developer-ready files with specs, tokens, and interaction documentation." },
    ],
    techStack: ["Figma", "FigJam", "Maze", "Hotjar", "Lottie", "Storybook", "Zeplin"],
    whyUs: [
      { title: "Systems thinking", description: "We design for the whole product, not individual screens in isolation." },
      { title: "Developer collaboration", description: "We stay involved through build to catch any design-dev gaps early." },
      { title: "Research-grounded", description: "Design decisions backed by user evidence, not assumptions." },
      { title: "Complexity made simple", description: "We specialise in making powerful, complex tools feel effortless." },
    ],
  },
  {
    slug: "digital-marketing",
    category: "marketing",
    title: "Digital Marketing",
    tagline: "Marketing that earns its budget.",
    heroDescription: "We plan and execute digital marketing strategies that drive qualified traffic, generate leads, and build brand equity — with clear attribution at every step.",
    icon: Megaphone,
    accentColor: "bg-[#FDE68A]",
    heroStats: [
      { value: "3x", label: "Avg. ROAS achieved" },
      { value: "Full-funnel", label: "Strategy" },
      { value: "Data-driven", label: "Every decision" },
    ],
    whatWeDo: {
      heading: "Marketing strategy that connects the dots.",
      body: "Digital marketing only works when the strategy, content, channels, and measurement all work together. We build full-funnel campaigns that attract the right audience and convert them consistently.",
      bullets: [
        "Integrated digital marketing strategy",
        "Paid search and paid social campaigns",
        "Content marketing and SEO",
        "Email marketing and automation",
        "Analytics, attribution, and reporting",
      ],
    },
    offerings: [
      { title: "Paid Search (PPC)", description: "Google Ads campaigns that capture demand at the moment of intent." },
      { title: "Paid Social", description: "Meta, LinkedIn, and TikTok campaigns that reach and convert your ideal audience." },
      { title: "Content Marketing", description: "Strategic content that builds authority and drives organic traffic." },
      { title: "Email Campaigns", description: "Segmented email sequences that nurture leads and retain customers." },
      { title: "Marketing Automation", description: "HubSpot, Mailchimp, or custom automations that work while you sleep." },
      { title: "Analytics & Reporting", description: "Clear dashboards that show what's working, what's not, and what to do next." },
    ],
    process: [
      { step: "01", title: "Audit", description: "Review your current channels, competitors, and market position." },
      { step: "02", title: "Strategy", description: "Define your ICP, messaging, channels, and budget allocation." },
      { step: "03", title: "Setup", description: "Tracking, pixels, UTMs, and integrations configured correctly from the start." },
      { step: "04", title: "Launch", description: "Campaigns go live with structured A/B tests built in." },
      { step: "05", title: "Optimise", description: "Weekly analysis and continuous improvement based on real performance data." },
      { step: "06", title: "Report", description: "Monthly reviews with clear attribution, insights, and next-quarter planning." },
    ],
    techStack: ["Google Ads", "Meta Ads", "HubSpot", "Mailchimp", "GA4", "Google Tag Manager", "Semrush", "Ahrefs"],
    whyUs: [
      { title: "Strategy before tactics", description: "We never run ads without knowing exactly who we're targeting and why." },
      { title: "Full attribution", description: "We track the full funnel so you know exactly what's driving revenue." },
      { title: "Cross-channel expertise", description: "Search, social, email, and content — coordinated, not siloed." },
      { title: "Transparent reporting", description: "Monthly reports in plain English with honest assessments and clear next steps." },
    ],
  },
  {
    slug: "seo-content",
    category: "marketing",
    title: "SEO & Content",
    tagline: "Rank for the terms that actually drive revenue.",
    heroDescription: "We combine technical SEO rigour with content strategy to build sustainable organic growth — the kind that compounds over time and doesn't disappear when you pause your ad spend.",
    icon: Search,
    accentColor: "bg-[#A7F3D0]",
    heroStats: [
      { value: "2x", label: "Avg. organic traffic growth" },
      { value: "Technical", label: "+ content SEO" },
      { value: "Long-term", label: "Growth focus" },
    ],
    whatWeDo: {
      heading: "SEO that builds an asset, not a dependency.",
      body: "Most SEO agencies optimise for rankings. We optimise for revenue. That means focusing on keywords with commercial intent, content that converts, and technical foundations that let your site compete for years.",
      bullets: [
        "Technical SEO audit and remediation",
        "Keyword research and content strategy",
        "On-page optimisation at scale",
        "Link building and digital PR",
        "Performance tracking and monthly reporting",
      ],
    },
    offerings: [
      { title: "Technical SEO", description: "Core Web Vitals, crawl health, schema markup, and everything under the hood." },
      { title: "Keyword Research", description: "Identifying the terms your ideal customers actually search for." },
      { title: "Content Strategy", description: "A publishing plan that targets the right topics in the right order." },
      { title: "Content Writing", description: "SEO-optimised articles and landing pages that rank and convert." },
      { title: "Link Building", description: "High-quality backlinks through outreach, digital PR, and partnerships." },
      { title: "Local SEO", description: "Dominate local search results for your city and service area." },
    ],
    process: [
      { step: "01", title: "Audit", description: "Full technical and content audit to establish a baseline and find quick wins." },
      { step: "02", title: "Research", description: "Keyword and competitor analysis to identify the highest-value opportunities." },
      { step: "03", title: "Technical Fix", description: "Resolve crawl errors, improve page speed, and fix structural issues." },
      { step: "04", title: "Content Plan", description: "A prioritised editorial calendar aligned to your commercial goals." },
      { step: "05", title: "Publish & Optimise", description: "Regular content publication and on-page optimisation." },
      { step: "06", title: "Build & Report", description: "Link building campaigns and monthly performance reporting." },
    ],
    techStack: ["Ahrefs", "Semrush", "Google Search Console", "Screaming Frog", "GA4", "Surfer SEO", "Notion"],
    whyUs: [
      { title: "Revenue-focused", description: "We measure success in qualified traffic and leads, not just rankings." },
      { title: "Technical depth", description: "We fix the underlying issues that hold sites back, not just the surface symptoms." },
      { title: "Content quality", description: "We write content humans want to read and search engines want to rank." },
      { title: "Transparent reporting", description: "Monthly reports that connect SEO activity to business outcomes." },
    ],
  },
  {
    slug: "social-media-marketing",
    category: "marketing",
    title: "Social Media Marketing",
    tagline: "A social presence worth following.",
    heroDescription: "We build and manage social media strategies that grow engaged audiences, build brand credibility, and drive real business outcomes — not just vanity metrics.",
    icon: ThumbsUp,
    accentColor: "bg-[#BAE6FD]",
    heroStats: [
      { value: "10x", label: "Avg. engagement growth" },
      { value: "All major", label: "Platforms covered" },
      { value: "Content +", label: "Community management" },
    ],
    whatWeDo: {
      heading: "Social media that builds a business, not just a following.",
      body: "Follower counts are vanity. We focus on the metrics that matter — reach, engagement quality, click-through, and ultimately, leads and revenue.",
      bullets: [
        "Platform-specific content strategy",
        "Content creation and copywriting",
        "Community management and engagement",
        "Paid social campaign management",
        "Monthly performance analysis and reporting",
      ],
    },
    offerings: [
      { title: "Content Strategy", description: "A platform-specific plan that aligns content to your audience and business goals." },
      { title: "Content Creation", description: "Graphics, short-form video, carousels, and copy — all produced in-house." },
      { title: "Community Management", description: "Timely, on-brand responses that build loyalty and handle issues professionally." },
      { title: "Instagram Marketing", description: "Feed, Stories, and Reels strategy for visual brands." },
      { title: "LinkedIn Marketing", description: "B2B authority building and lead generation through LinkedIn." },
      { title: "Paid Social", description: "Meta and LinkedIn ads that amplify your best content and target new audiences." },
    ],
    process: [
      { step: "01", title: "Audit", description: "Assess your current social presence, audience, and competitive landscape." },
      { step: "02", title: "Strategy", description: "Define platforms, content pillars, posting cadence, and KPIs." },
      { step: "03", title: "Content Plan", description: "Monthly content calendar approved before publishing." },
      { step: "04", title: "Create & Publish", description: "All content created, scheduled, and published on your behalf." },
      { step: "05", title: "Engage", description: "Daily community management across all active platforms." },
      { step: "06", title: "Review", description: "Monthly performance report with insight-led recommendations." },
    ],
    techStack: ["Meta Business Suite", "Buffer", "Hootsuite", "Canva", "CapCut", "LinkedIn Campaign Manager", "Sprout Social"],
    whyUs: [
      { title: "Content quality first", description: "We won't publish content that doesn't meet the brand standard, full stop." },
      { title: "Platform specialists", description: "What works on LinkedIn is different to what works on Instagram — we know the difference." },
      { title: "Consistency guaranteed", description: "A reliable publishing cadence maintained regardless of how busy you are." },
      { title: "Results over vanity", description: "We report on engagement quality, reach, and conversions — not just follower counts." },
    ],
  },
  {
    slug: "ecommerce-solutions",
    category: "development",
    title: "E-commerce Solutions",
    tagline: "Online stores built to convert.",
    heroDescription: "We design and build e-commerce experiences that make buying easy, build trust, and maximise revenue — from your first store to a full enterprise commerce platform.",
    icon: ShoppingCart,
    accentColor: "bg-[#FDE68A]",
    heroStats: [
      { value: "20+", label: "Stores launched" },
      { value: "Shopify", label: "+ custom builds" },
      { value: "CRO", label: "Built-in from day one" },
    ],
    whatWeDo: {
      heading: "Commerce designed around how customers actually buy.",
      body: "The best-looking store in the world won't sell if checkout is clunky, product pages don't convert, or the mobile experience falls apart.",
      bullets: [
        "Shopify and custom-built store development",
        "Product page and checkout optimisation",
        "Payment gateway and fulfilment integration",
        "Inventory and order management systems",
        "Performance and conversion rate optimisation",
      ],
    },
    offerings: [
      { title: "Shopify Development", description: "Custom Shopify themes and app integrations for growth-focused brands." },
      { title: "Custom E-commerce", description: "Bespoke stores built from scratch when Shopify isn't the right fit." },
      { title: "Checkout Optimisation", description: "Reduce cart abandonment with a streamlined, trust-building checkout flow." },
      { title: "Payment Integration", description: "Stripe, PayPal, Klarna, and local payment methods configured correctly." },
      { title: "Headless Commerce", description: "Decouple your frontend from your commerce engine for maximum performance." },
      { title: "Migration", description: "Move from WooCommerce, Magento, or any other platform to Shopify without losing data." },
    ],
    process: [
      { step: "01", title: "Discovery", description: "Understand your products, customers, and current conversion blockers." },
      { step: "02", title: "Design", description: "Product pages, category pages, and checkout designed for conversion." },
      { step: "03", title: "Development", description: "Build and integrate the store with your fulfilment and inventory systems." },
      { step: "04", title: "Testing", description: "Full purchase flow testing across devices and payment methods." },
      { step: "05", title: "Launch", description: "Smooth go-live with analytics, search console, and uptime monitoring configured." },
      { step: "06", title: "Optimise", description: "Post-launch CRO using real data to improve conversion continuously." },
    ],
    techStack: ["Shopify", "Next.js", "Stripe", "PayPal", "Klaviyo", "Google Analytics", "Vercel", "Sanity"],
    whyUs: [
      { title: "Conversion-first design", description: "Every element earns its place by helping customers buy with confidence." },
      { title: "Performance obsessed", description: "Slow stores lose sales. We build for speed as a feature, not an afterthought." },
      { title: "Post-launch optimisation", description: "We use real traffic data to improve your conversion rate after launch." },
      { title: "Platform expertise", description: "Shopify, headless, or custom — we recommend what's right for your business." },
    ],
  },
  {
    slug: "ai-automation",
    category: "development",
    title: "AI & Automation",
    tagline: "Work smarter. Scale without headcount.",
    heroDescription: "We help businesses leverage AI and intelligent automation to eliminate repetitive work, surface better insights, and build capabilities that would otherwise require a much larger team.",
    icon: Bot,
    accentColor: "bg-[#C4B5FD]",
    heroStats: [
      { value: "70%", label: "Avg. time saved on automated tasks" },
      { value: "LLM", label: "+ workflow automation" },
      { value: "Custom", label: "AI solutions" },
    ],
    whatWeDo: {
      heading: "AI that solves real problems, not hype-driven experiments.",
      body: "We cut through the noise and focus on where AI and automation can deliver genuine ROI for your business — whether that's a document processing pipeline, an intelligent chatbot, or a fully automated workflow.",
      bullets: [
        "AI strategy and use-case identification",
        "LLM-powered applications and chatbots",
        "Document processing and data extraction",
        "Workflow and process automation",
        "API integration with AI services",
      ],
    },
    offerings: [
      { title: "AI Chatbots", description: "LLM-powered assistants trained on your data and integrated into your product." },
      { title: "Document Automation", description: "Extract, classify, and process documents without manual review." },
      { title: "Workflow Automation", description: "Connect your tools and automate multi-step processes end to end." },
      { title: "Data Pipeline Automation", description: "Automated data collection, transformation, and reporting workflows." },
      { title: "AI Integration", description: "Add OpenAI, Anthropic, or custom model capabilities to your existing product." },
      { title: "Predictive Analytics", description: "Surface patterns and predictions from your data to drive better decisions." },
    ],
    process: [
      { step: "01", title: "Discovery", description: "Identify your highest-value automation and AI opportunities." },
      { step: "02", title: "Solution Design", description: "Design the architecture and choose the right AI models and tools." },
      { step: "03", title: "Prototype", description: "Build a working proof of concept to validate the approach before full build." },
      { step: "04", title: "Build", description: "Production-grade implementation with error handling and monitoring." },
      { step: "05", title: "Test", description: "Accuracy testing, edge-case handling, and performance validation." },
      { step: "06", title: "Deploy & Monitor", description: "Production deployment with ongoing monitoring and model improvement." },
    ],
    techStack: ["OpenAI", "Anthropic", "LangChain", "Python", "Node.js", "Zapier", "Make.com", "AWS Lambda", "Pinecone"],
    whyUs: [
      { title: "ROI-first thinking", description: "We only recommend AI where it will genuinely save time or make money." },
      { title: "End-to-end delivery", description: "Strategy, build, and deployment from one team, not three different vendors." },
      { title: "Practical experience", description: "We've built real AI systems in production — not just prototypes." },
      { title: "Responsible AI", description: "We build with appropriate safeguards, oversight, and data governance built in." },
    ],
  },
  {
    slug: "cloud-devops",
    category: "development",
    title: "Cloud & DevOps",
    tagline: "Infrastructure that scales. Deployments that don't break.",
    heroDescription: "We design and manage cloud infrastructure and DevOps pipelines that are secure, cost-efficient, and built to scale — so your engineering team can ship with confidence.",
    icon: Cloud,
    accentColor: "bg-[#BAE6FD]",
    heroStats: [
      { value: "99.9%", label: "Uptime target achieved" },
      { value: "AWS", label: "+ GCP + Azure" },
      { value: "CI/CD", label: "From day one" },
    ],
    whatWeDo: {
      heading: "Infrastructure built for reliability, not just launch day.",
      body: "Good DevOps isn't about the tools — it's about building a system where deployments are routine, incidents are caught early, and engineering teams spend their time shipping features, not fighting fires.",
      bullets: [
        "Cloud architecture design and implementation",
        "CI/CD pipeline setup and automation",
        "Infrastructure as Code with Terraform",
        "Containerisation and Kubernetes orchestration",
        "Security, compliance, and cost optimisation",
      ],
    },
    offerings: [
      { title: "Cloud Architecture", description: "AWS, GCP, or Azure — designed for your scale, your budget, and your team." },
      { title: "CI/CD Pipelines", description: "Automated build, test, and deployment pipelines that ship code safely." },
      { title: "Infrastructure as Code", description: "Terraform and CloudFormation so your infrastructure is version-controlled." },
      { title: "Containerisation", description: "Docker and Kubernetes for consistent, portable, and scalable deployments." },
      { title: "Monitoring & Alerting", description: "Observability setup so you know about problems before your users do." },
      { title: "Security & Compliance", description: "IAM policies, secrets management, and compliance controls properly configured." },
    ],
    process: [
      { step: "01", title: "Audit", description: "Review your current infrastructure, costs, and reliability gaps." },
      { step: "02", title: "Architecture", description: "Design the right cloud setup for your stage, scale, and team size." },
      { step: "03", title: "IaC", description: "Codify your infrastructure with Terraform so it's repeatable and version-controlled." },
      { step: "04", title: "CI/CD", description: "Set up automated pipelines for safe, consistent deployments." },
      { step: "05", title: "Observability", description: "Logging, metrics, tracing, and alerting configured across the stack." },
      { step: "06", title: "Handover", description: "Documentation, runbooks, and team training so you own what we build." },
    ],
    techStack: ["AWS", "GCP", "Azure", "Terraform", "Docker", "Kubernetes", "GitHub Actions", "Datadog", "Grafana"],
    whyUs: [
      { title: "Right-sized for your stage", description: "We won't over-engineer for scale you don't have — or under-engineer for scale you will." },
      { title: "Security by default", description: "Security isn't bolted on at the end — it's designed in from the architecture phase." },
      { title: "Cost optimisation", description: "We regularly audit and right-size infrastructure so you're not paying for idle resources." },
      { title: "Knowledge transfer", description: "We document everything and train your team — you own your infrastructure." },
    ],
  },
];

export function getServiceBySlug(slug: string): ServiceData | undefined {
  return servicesData.find((s) => s.slug === slug);
}

export function getAllServiceSlugs(): string[] {
  return servicesData.map((s) => s.slug);
}

export function getServicesByCategory(category: ServiceData["category"]): ServiceData[] {
  return servicesData.filter((s) => s.category === category);
}

export type ServiceCategory = "development" | "design" | "marketing";

export const categoryMeta: Record<ServiceCategory, { label: string; description: string }> = {
  development: {
    label: "Development",
    description: "From custom software to mobile apps, SaaS platforms to cloud infrastructure — we engineer digital products that scale.",
  },
  design: {
    label: "Design",
    description: "UI/UX, brand identity, graphic design, and digital product design — we craft experiences that are intuitive, beautiful, and on-brand.",
  },
  marketing: {
    label: "Marketing",
    description: "Digital marketing, SEO, social media — we build strategies that drive qualified traffic, generate leads, and grow your brand.",
  },
};
